# Generated by Django 5.2.8 on 2025-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='provider',
            new_name='sponsor',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
