# Generated by Django 5.2.8 on 2025-11-25 11:26

import apps.main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.main.models.UserManager()),
            ],
        ),
    ]
